# OKX Python wrapper
# Keeps Python runtime environment local to OKX jobs without changing global env.
# Usage:
#   pwsh -NoProfile -File <PROJECT_ROOT>\scripts\run_okx_python.ps1 <PROJECT_ROOT>\scripts\collect_data.py --profile live --db-root <PROJECT_ROOT>\db

$ErrorActionPreference = 'Stop'

# v7.0e.3→v7.0e.4 修复：显式设 UTF-8 防 GBK pipe（三向：stdin/stdout/stderr）
# 根因：Get-Content | pwsh 管道中 PS 默认 $OutputEncoding 可能是 ASCII/ANSI，
# 含中文 JSON 经 pipe 到 python stdin 时被 GBK 截断产生 surrogate 错（udcae）。
# 修复：三向全设 UTF-8 + $PSDefaultParameterValues 兜底。
try {
    [Console]::InputEncoding  = [System.Text.Encoding]::UTF8
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $OutputEncoding = [System.Text.Encoding]::UTF8
    $PSDefaultParameterValues['*:Encoding'] = 'utf8'
} catch {
    # 静默失败：部分 PS 版本不支持，python 端已有 sys.stdout.reconfigure(encoding='utf-8') 兜底
}

if ($args.Count -lt 1) {
    Write-Error "Usage: run_okx_python.ps1 <python-script-or-args> [args...]"
    exit 64
}

$okxRoot = if ([string]::IsNullOrWhiteSpace($env:OKX_ROOT)) {
    Split-Path -Parent $PSScriptRoot
} else {
    [System.IO.Path]::GetFullPath($env:OKX_ROOT)
}
$pythonExe = if ([string]::IsNullOrWhiteSpace($env:OKX_PYTHON_BIN)) {
    $cmd = Get-Command python -ErrorAction SilentlyContinue
    if ($null -eq $cmd) {
        Write-Error "Python was not found. Set OKX_PYTHON_BIN to a Python executable."
        exit 65
    }
    $cmd.Source
} else {
    $env:OKX_PYTHON_BIN
}
$okxSitePackages = if ([string]::IsNullOrWhiteSpace($env:OKX_SITE_PACKAGES)) {
    Join-Path $okxRoot 'Lib\site-packages'
} else {
    $env:OKX_SITE_PACKAGES
}

# Keep generated bytecode/cache artifacts out of scripts/ and db/.
$env:PYTHONDONTWRITEBYTECODE = '1'
$env:PYTHONPYCACHEPREFIX = Join-Path $okxRoot 'tmp\pycache'
# v2 (2026-06-29)：同时把 $okxRoot 入 PYTHONPATH，让 tmp/* 探针脚本可 `import collectors.*/core.*/scripts.*`。
# 根因：wrapper 原只加 site-packages；agent 写的 tmp 脚本 sys.path[0]=脚本自身的 tmp 目录、cwd(<PROJECT_ROOT>)
# 不自动入 sys.path，故 `from collectors.ledger import ...` 报 ModuleNotFoundError（见 v2-agent-phantom-reads）。
# 有本地依赖目录时优先加载；公开版默认不包含 Lib/，会直接使用所选 Python 的环境。
$ppParts = @()
if (Test-Path -LiteralPath $okxSitePackages) { $ppParts += $okxSitePackages }
$ppParts += $okxRoot
if (-not [string]::IsNullOrWhiteSpace($env:PYTHONPATH)) { $ppParts += ($env:PYTHONPATH -split ';') }
$env:PYTHONPATH = ($ppParts | Where-Object { $_ } | Select-Object -Unique) -join ';'

# 代理优先取显式环境变量；未配置时仅采用当前启用的 WinINET 系统代理。
$okxProxy = $env:OKX_PROXY_URL
if ([string]::IsNullOrWhiteSpace($okxProxy)) {
    try {
        $ie = Get-ItemProperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings' -ErrorAction Stop
        if ([int]$ie.ProxyEnable -eq 1 -and -not [string]::IsNullOrWhiteSpace($ie.ProxyServer)) {
            $okxProxy = [string]$ie.ProxyServer
            if ($okxProxy -match 'https=([^;]+)') { $okxProxy = $matches[1] }
            elseif ($okxProxy -match 'http=([^;]+)') { $okxProxy = $matches[1] }
            if ($okxProxy -notmatch '^\w+://') { $okxProxy = "http://$okxProxy" }
        }
    } catch { }
}
if (-not [string]::IsNullOrWhiteSpace($okxProxy)) {
    $env:OKX_PROXY_URL = $okxProxy
    if ([string]::IsNullOrWhiteSpace($env:HTTPS_PROXY)) { $env:HTTPS_PROXY = $okxProxy }
    if ([string]::IsNullOrWhiteSpace($env:HTTP_PROXY))  { $env:HTTP_PROXY  = $okxProxy }
}

# 妙想 API key 兜底：env 缺失时从 config.md §4.4 grep 注入（与 collect_data.py / collect_slow.py 同步）
if ([string]::IsNullOrWhiteSpace($env:MX_APIKEY)) {
    $configPath = Join-Path $okxRoot 'config.md'
    if (Test-Path $configPath) {
        try {
            $cfgContent = Get-Content $configPath -Raw -Encoding UTF8
            # v7.0e.3 修复：原 `[^|`\s]` 排除反引号，导致 §4.4 含 `MX_APIKEY` 反引号的行匹配失败穿透到 §4.5；改用 `[^|\s]`
            $mxMatch = [regex]::Match($cfgContent, '###\s+4\.4 妙想资讯.*?\|\s*API Key\s*\|\s*([^|\s][^|]*?)\s*\|', [System.Text.RegularExpressions.RegexOptions]::Singleline)
            if ($mxMatch.Success) {
                $mxValue = $mxMatch.Groups[1].Value.Trim().Trim([char]96).Trim()
                if (-not ($mxValue.StartsWith('<') -and $mxValue.EndsWith('>'))) {
                    $env:MX_APIKEY = $mxValue
                }
            }
        } catch {
            # 静默失败：env 缺失会让 Python 端兜底再试一次
        }
    }
}

if (Test-Path $okxRoot) {
    Set-Location $okxRoot
}

& $pythonExe @args
exit $LASTEXITCODE
